---
date: "2016-04-27T00:00:00Z"
external_link: ""
image:
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
links:
- icon: github
  icon_pack: fab
  name: Material for my students Tunisianfirm package
  url: https://github.com/Foha2001/tunisianfirms
#slides: example
summary: Package presentation.
tags:
- Deep Learning
title: Tunisianfirms package
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---


```{r}

#The goal of tunisianfirms is to spread cotation of Tunisian stock Exchange Firms

#Installation
#Coming soon You can install the released version of tunisianfirms from CRAN with:

#install.packages("tunisianfirms")
#or

#install.packages("tunisianfirms")
library(devtools)
#devtools::install_github("Foha2001/tunisianfirms")
#you have to install devtools before, when installing from github
library(tunisianfirms)
## basic example code
cotation("ATTIJARIBANK")

```
<!-- Example -->
<!-- This is a basic example which shows you how to solve a common problem: -->
```{r}

head(sample_data)
```




